---
layout: cv
title: Travis Parrish's CV
---
## Education
B.A. in Accounting, BYU-Idaho	                            Expected in 2027

## Employment 
### Tutor/T.A., BYU-I
Rexburg, ID                                                 Apr 2025—Apr 2026

•	Help students with any questions they may have.
•	Be aware of my surroundings to know when someone needs help and know what kind of help they are looking for.

### Cleaning/Shipping, SanTan Solar
Chandler, AZ                                                Sep 2024—Nov 2024, Oct 2021—Mar 2022

•	Attention to detail was important to ensure that orders had the correct solar panels, were stacked securely, and that they were properly packaged to prevent damage while shipping.
•	Driving a forklift required me to be observant of my surroundings for the safety of others and of the product.

### Product Flow, Best Buy	
Gilbert, AZ                                                 Oct 2023—Oct 2024

●	Attention to detail was required to ensure that product was in the correct place and had any required security tags. Also needed to ensure that all inventory was accounted for.
●	Consistent and fast-paced work was required to unload delivery trucks in a timely manner.

### Guest Advocate, Target	   
Gilbert, AZ                                                 Mar 2022—Oct 2023

●	Observe and assist any customers while they were shopping or purchasing their items. Make sure they felt good about what they were buying.
●	Move quickly and safely while delivering curbside orders for my safety, safety of vehicles in the parking lot, and the safety of the purchased items. Needed to be aware of my surroundings to make sure that I was not hit by a car.

## Other Experience
### Full-time Missionary, Arizona Tempe-Chandler Service Mission
                                                            Sep 2019—Sep 2021

●	Administrative Assistant to the Development Counselor at the Gilbert Deseret Industries (DI). Contacted bishops to let them know if DI is hiring. Scheduled appointments for the Development Counselor for prospective hires and also associates.
●	Helped create, develop, and teach the first Service Missionary Training Center (SMTC).
●	Served as a District Leader, Zone Leader, and Assistant to the Mission Leaders. Helped with Training new missionaries and organizing mission activities.
	


## Skills
* Attentive to Detail
* Leader	

## Awards & Honors
* Poway High School Honor Award
* Forklift Certification	

## Projects
* Used Excel XLOOKUP, SUMIFS, and COUNTIFS to show relevant information	

